services:
  app:
    image: fastapi-playground
    command: uv run fastapi run src/main.py
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.swarm.network=traefik"
        - "traefik.enable=true"
        - "traefik.http.routers.fastapi.rule=Host(`fastapi.backend.marcmarina.com`)"
        - "traefik.http.routers.fastapi.entrypoints=web"
        - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

networks:
  traefik:
    external: true
